### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by coretemp** [carlpett/terraform-sops#3]
Please add a license. 

It would also be useful to have something that we can run in an unimportant Amazon account to test that this works. 

Similarly, some kind of intention of whether you actually want (or recommend anyone else to use this would also be useful).

**Comment by coretemp** [comment]
It would be nice if you could do a PR to https://github.com/NixOS/nixpkgs adding this as a terraform-provider, but if you don't want to, you can also close this issue. It would make the decision to adopt this much easier.

I don't require any testing looking at it again. I thought it was doing more things, but the scope of this tool is fairly small (which is a good thing(!)).

**Comment by carlpett** [comment]
I'm not familiar with NixOS packaging, so have to see when I have time to dedicate to get familiar with it. Thanks for the suggestion, though!
Since it isn't related to the license file, I'll close this for now.
